[hyrax_alerts.writers.to_disk_0]
writer_class = "HyraxAlertsDiskWriter"
output_location = "./results"
post_process = "hyrax_alerts.example_functions.example_post_process"
post_filter = "hyrax_alerts.example_functions.example_post_filter"

[hyrax_alerts.writers.to_slack_0]
writer_class = "HyraxAlertsSlackWriter"
slack_token = false. # replace with slack bot token
channel = "#hyrax-alerts-test"  # DiRAC workspace slack channel
max_object_ids = 10

[data_request.infer_stream.data]
dataset_class = "hyrax_alerts.consumers.kafka_consumer.HyraxKafkaConsumer"
data_location = "kafka://localhost:9092/my-topic"
primary_id_field = "id"
fields = ["image", "label"]

[hyrax_alerts.consumer]
pre_process = "hyrax_alerts.example_functions.example_pre_process"
pre_filter = "hyrax_alerts.example_functions.example_pre_filter"

[model]
name = "HyraxLoopback"

[infer_stream]
model_weights_file = "./foo.bar"
save_model_output = true