[data_request.infer_stream.data]
dataset_class = "hyrax_alerts.consumers.kafka_consumer.HyraxKafkaConsumer"
data_location = "kafka://localhost:9092/my-topic"
primary_id_field = "id"
fields = ["image", "label"]

[hyrax_alerts.consumer]
pre_process = "hyrax_alerts.example_functions.example_pre_process"
pre_filter = "hyrax_alerts.example_functions.example_pre_filter"
